[package]
name = "cornfig"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple and pain-free configuration language."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"
serde_yaml = "0.8.23"
colored = "2.0.0"
clap = { version = "3.0.11", features = ["derive"] }
toml = "0.5.8"

[dev-dependencies]
paste = "1.0.6"