[package]
name = "libcorn"
version = "0.6.1"
edition = "2021"
license = "MIT"
description = "Parsing engine for Corn, a simple and pain-free configuration language."
repository = "https://github.com/JakeStanger/corn"
keywords = ["configuration", "language", "wasm", "pest", "peg"]

[features]
wasm = ["wasm-bindgen", "serde-wasm-bindgen", "console_error_panic_hook", "wee_alloc"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.6.0"
pest_derive = "2.6.0"
cfg-if = "1.0.0"
serde = { version = "1.0.133", features = ["derive"] }
thiserror = "1.0.40"
toml = "0.5.9" # currently required to work around toml serializing
wasm-bindgen = { version = "0.2.83", optional = true }
serde-wasm-bindgen = { version = "0.4.5", optional = true }
console_error_panic_hook = { version = "0.1.7", optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
paste = "1.0.6"
wasm-bindgen-test = { version = "0.3.29" }
# required for testing
serde_json = "1.0.75"
serde_yaml = "0.9.11"
