name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Update Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check

    - name: Cargo Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings

    - name: Cargo Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --profile release
      env:
        CORN_TEST: foobar

    - name: Wasm-Pack Test
      run: wasm-pack test --node
